### ISSUE TITLE
Error: spawn gofumpt ENOENT

### ISSUE THREAD

**Issue by roethke** [harry-hov/vscode-gno#2]
I am experiencing an error while using the Gno extension within VS.

This error occurs **on-save**; presently I have syntax highlighting but no `auto-fmt`, `auto-import`, etc. **on-save** likely due to this error.

**Output**
<img width="308" alt="Screenshot 2023-06-27 at 3 37 01 PM" src="https://github.com/harry-hov/vscode-gno/assets/17755587/52b00138-5381-4369-bf8d-a051ad2cf78a">

**Error**
<img width="429" alt="Screenshot 2023-06-27 at 3 33 01 PM" src="https://github.com/harry-hov/vscode-gno/assets/17755587/90518886-86de-475d-8503-f7840a426068">

**Comment by harry-hov** [comment]
Thanks for reporting this. I would like to know few more things about your system.
- do you have `gofumpt` installed in your system? 
- if yes, what's the output of `gofumpt --version`?

**Comment by roethke** [comment]
Yep, version: `v0.5.0 (go1.19)`

**Comment by harry-hov** [comment]
can you also provide the OS version (e.g. Windows 10)?

If you are running on a Windows system I've seen similar errors happening when the System Environment variable PATH does not include the CLI's path.

**Comment by roethke** [comment]
**OS**
Ventura 13.4 (macOS)

**VS Code**
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0 (**M1**)

**Comment by harry-hov** [comment]
This error usually happens when the command does not exist in your terminal or not available in the PATH. 

Make sure `gofumpt` is available in your default terminal used by VS Code. 

You can try (if you're using zsh as default terminal in you macOS): 
```md
   - Open zsh shell configuration file
  
       nano ~/.zshrc

   - Add line given below to the file

        export PATH="${PATH}:${GOPATH}/bin"
```
And restarting VS Code after this.

**Comment by roethke** [comment]
Thank you, the issue seems to be resolved for now
