### ISSUE TITLE
Publish on Open VSX registry

### ISSUE THREAD

**Issue by thehowl** [harry-hov/vscode-gno#4]
Hey Hariom, another feature request :)

We set up vscode-gno for use on the [getting-started](https://github.com/gnolang/getting-started) repo, as Gitpod is using a modified version of VS Code so the extension was perfect for that.

We managed to workaround Gitpod's instruction by using a direct link to downloading the extension; however Gitpod suggests using the [open vsx registry](https://open-vsx.org/) for extensions.

Is this something you can do? Thanks!

**Comment by harry-hov** [comment]
Hey, Sorry for taking long. Need to setup up a few accounts just to publish the extension on [open vsx registry](https://open-vsx.org/). I still need to get verified as a publisher. (seems like a long and painful process, so will do that later)

Meanwhile, I have published the extension. 
Link: https://open-vsx.org/extension/harry-hov/gno

Let me know if it works. Thanks!

**Comment by thehowl** [comment]
Just merged a PR to use the open vsx registry. Thanks!

https://github.com/gnolang/getting-started/pull/23
